apiVersion: v1
kind: Service
metadata:
  name: go-test
  namespace: cbai-default
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: go-test
  sessionAffinity: None
  type: ClusterIP